export var Cities = [
  "Abottabad",
  "Badin",
  "Bannu",
  "Bhawalpur",
  "Chakwal",
  "Dera Ismail Khan",
  "D G Khan",
  "Faisalabad",
  "Gawadar",
  "Ghotki",
  "Gilgit",
  "Gujranwala",
  "Gujrat",
  "Hyderabad",
  "Islamabad",
  "Jamshoro",
  "Jhelum",
  "Karachi",
  "Kashmir",
  "KhairPur",
  "Khanewal",
  "Kohat",
  "Lahore",
  "Larkana",
  "Mardan",
  "MirpurKhas",
  "Multan",
  "Muree",
  "NawabShah",
  "Peshawar",
  "Quetta",
  "Rahim Yar Khan",
  "RawalPindi",
  "Sahiwal",
  "Sargodha",
  "ShikarPur",
  "Sialkot",
  "Sibi",
  "Sukkar",
  "Swat",
  "Thatta",
  "Umerkot",
];

export var ShipmentTypes=['Electronics','Garments','Food','Glassware','Others...'];

export var AuctionDuration=[
  { label:'1 Day',val:1 },{ label:'2 Day',val:2 },{ label:'3 Day',val:3 },{ label:'4 Day',val:4 }];

  export var Provinces = ['Khyber Pakhtunkhwa','Balochistan','Punjab','Sindh']